### PR TITLE
Fix invisible gutter

### PR DESCRIPTION
**Pull request by Cxarli**
Fix by @hossamyehia

### CODE REVIEW

**Comment by CrazyAnchovy** [comment]
https://github.com/abe33/atom-pigments/issues/383#issuecomment-527643236

the above worked for me but it made the circle dot appear at the beginning of the line, overlapping the first character. square-dot is working

windows 10
atom 1.48.0
pigments 0.40.2

**Comment by dvigne** [comment]
This fix also worked for me. No issues thus far.

**Comment by Cxarli** [comment]
I can't issue a new release on apm, but I'll release it to master so people can pull it manually

**Comment by dvigne** [comment]
Thanks @Cxarli. That's what I did on my computer. I just checked out the hossamyehia-patch branch on my computer and pulled it manually from there.

**Pull request merged**
