### PR TITLE
Add a new setting to show color variable value in autocomplete

### PR DESCRIPTION
**Pull request by dzhiriki**
Implement suggestion from #140

### CODE REVIEW

**Comment by dzhiriki** [comment]
Yeah, you're right. I didn't think about this way. Fixed.

**Comment by abe33** [comment]
Great, thank you, don't mind the builds failure, it seems like an issue specific to beta that I'll fix later. 

Do you mind adding a few test for this setting in the provider specs (https://github.com/abe33/atom-pigments/blob/master/spec/pigments-provider-spec.coffee)?

**Comment by dzhiriki** [comment]
Oh, sorry, I didn't have time to write tests. And you did it first :)

**Comment by abe33** [comment]
No problem, it wasn't that much to write :)

**Pull request merged**
