### PR TITLE
Fix for dot markers overlapping text – part of issue #178.

### PR DESCRIPTION
**Pull request by richrad**

### CODE REVIEW

**Comment by abe33** [comment]
Nice catch, I didn't noticed that the new way to compute the dot position in the line was making them overlapping the text.

**Comment by jish** [comment]
Just curious, what does the release cycle for this project look like? When will there be a new release with this fix?

**Comment by abe33** [comment]
Hi, I'm currently working on a version that will use native decorations instead. This should help fixing these positioning inconsistencies. I plan to release a version soon with both versions (custom decorations vs native decorations) so that people can try them without being forced to use them if they see a problem.

**Comment by jish** [comment]
Cool. Thanks for the update! :)

**Comment by abe33** [comment]
I just published the mentioned version as 0.27 🎉 

Let me know if it improved things for you.

**Comment by jish** [comment]
It is not overlapping for me anymore, thanks 😄 

screen shot 2016-06-02 at 9 47 20 am

**Pull request merged**
