### PR TITLE
Basic support for atom>=1.19 new renderer

### LINKED ISSUE #314: Failed to activate the pigments package
The following startup error occurs on **_Atom 1.19.0-beta0_**. 
```
Failed to activate the pigments package.
Cannot find 'highlights-component' in the require cache .
```

**Stack Trace:**
```
Cannot find 'highlights-component' in the require cache.
Hide Stack Trace
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
```

**General Question:**
Is there also a bug to be created in the sense that this is a new issue and not the same as the [2016 bug here](https://github.com/abe33/atom-pigments/issues/201)? It would be amazing to be able to say `nope, this is indeed a new issue`.

### PR DESCRIPTION
**Pull request by Greenek**
Fixes #314, #318 

zrzut ekranu 2017-07-25 o 03 16 48

### CODE REVIEW

**Comment by maksim-litvinov** [comment]
Looks like everything works in 0.40 version

**Comment by mbokil** [comment]
Thanks for updating it. I can use the beta again. Much appreciated!

**Comment by abe33** [comment]
Hi there, sorry I didn't saw your PR earlier, I just fixed that in v0.40, thanks for taking the time to contribute thought.

**Comment by Greenek** [comment]
@abe33 no problem!

**Pull request closed without merging**
